import { useSession } from "next-auth/react";
import { ChangeEvent, useCallback, useEffect, useMemo, useReducer } from "react";
import { useTranslation } from "react-i18next";
import DragDrop from "brancy/components/design/dragDrop/dragDrop";
import TextArea from "brancy/components/design/textArea/textArea";
import NotAllowedCard from "brancy/components/notOk/notAllowedCard";
import { RoleAccess } from "brancy/helper/loadingStatus";
import { LanguageKey } from "brancy/i18n";
import { PartnerRole } from "brancy/models/_AccountInfo/InstagramerAccountInfo";
import styles from "./customFont.module.css";
interface FontMap {
  [key: string]: {
    [key: string]: string;
  };
}
type FontState = {
  isHidden: boolean;
  inputText: string;
  selectedFont: string;
  copied: string;
  convertedText: string;
};

type FontAction =
  | { type: "TOGGLE_HIDDEN" }
  | { type: "SET_INPUT_TEXT"; payload: string }
  | { type: "SET_SELECTED_FONT"; payload: string }
  | { type: "SET_COPIED"; payload: string }
  | { type: "SET_CONVERTED_TEXT"; payload: string }
  | { type: "RESET_COPIED" };

const fontReducer = (state: FontState, action: FontAction): FontState => {
  switch (action.type) {
    case "TOGGLE_HIDDEN":
      return { ...state, isHidden: !state.isHidden };
    case "SET_INPUT_TEXT":
      return { ...state, inputText: action.payload };
    case "SET_SELECTED_FONT":
      return { ...state, selectedFont: action.payload };
    case "SET_COPIED":
      return { ...state, copied: action.payload };
    case "SET_CONVERTED_TEXT":
      return { ...state, convertedText: action.payload };
    case "RESET_COPIED":
      return { ...state, copied: "" };
    default:
      return state;
  }
};
const convertTextHelper = (text: string, style: string, map: FontMap): string => {
  return text
    .split("")
    .map((char) => map[style]?.[char] || map[style]?.[char.toLowerCase()] || char)
    .join("");
};

export default function FontSelector() {
  const { t } = useTranslation();
  const { data: session } = useSession();
  const hasAccess = useMemo(() => RoleAccess(session, PartnerRole.PageView), [session]);

  const fontMap: FontMap = useMemo(
    () => ({
      SANS_sans: {
        /* mapping for sans */
        A: "𝖠",
        B: "𝖡",
        C: "𝖢",
        D: "𝖣",
        E: "𝖤",
        F: "𝖥",
        G: "𝖦",
        H: "𝖧",
        I: "𝖨",
        J: "𝖩",
        K: "𝖪",
        L: "𝖫",
        M: "𝖬",
        N: "𝖭",
        O: "𝖮",
        P: "𝖯",
        Q: "𝖰",
        R: "𝖱",
        S: "𝖲",
        T: "𝖳",
        U: "𝖴",
        V: "𝖵",
        W: "𝖶",
        X: "𝖷",
        Y: "𝖸",
        Z: "𝖹",
        a: "𝖺",
        b: "𝖻",
        c: "𝖼",
        d: "𝖽",
        e: "𝖾",
        f: "𝖿",
        g: "𝗀",
        h: "𝗁",
        i: "𝗂",
        j: "𝗃",
        k: "𝗄",
        l: "𝗅",
        m: "𝗆",
        n: "𝗇",
        o: "𝗈",
        p: "𝗉",
        q: "𝗊",
        r: "𝗋",
        s: "𝗌",
        t: "𝗍",
        u: "𝗎",
        v: "𝗏",
        w: "𝗐",
        x: "𝗑",
        y: "𝗒",
        z: "𝗓",
      },
      SERIF_serif: {
        /* mapping for serif */
        a: "𝔞",
        b: "𝔟",
        c: "𝔠",
        d: "𝔡",
        e: "𝔢",
        f: "𝔣",
        g: "𝔤",
        h: "𝔥",
        i: "𝔦",
        j: "𝔧",
        k: "𝔨",
        l: "𝔩",
        m: "𝔪",
        n: "𝔫",
        o: "𝔬",
        p: "𝔭",
        q: "𝔮",
        r: "𝔯",
        s: "𝔰",
        t: "𝔱",
        u: "𝔲",
        v: "𝔳",
        w: "𝔴",
        x: "𝔵",
        y: "𝔶",
        z: "𝔷",
      },
      BOLD_bold: {
        /* mapping for bold */
        a: "𝐚",
        b: "𝐛",
        c: "𝐜",
        d: "𝐝",
        e: "𝐞",
        f: "𝐟",
        g: "𝐠",
        h: "𝐡",
        i: "𝐢",
        j: "𝐣",
        k: "𝐤",
        l: "𝐥",
        m: "𝐦",
        n: "𝐧",
        o: "𝐨",
        p: "𝐩",
        q: "𝐪",
        r: "𝐫",
        s: "𝐬",
        t: "𝐭",
        u: "𝐮",
        v: "𝐯",
        w: "𝐰",
        x: "𝐱",
        y: "𝐲",
        z: "𝐳",
      },
      SCRIPT_script: {
        /* mapping for script */
        a: "𝓪",
        b: "𝓫",
        c: "𝓬",
        d: "𝓭",
        e: "𝓮",
        f: "𝓯",
        g: "𝓰",
        h: "𝓱",
        i: "𝓲",
        j: "𝓳",
        k: "𝓴",
        l: "𝓵",
        m: "𝓶",
        n: "𝓷",
        o: "𝓸",
        p: "𝓹",
        q: "𝓺",
        r: "𝓻",
        s: "𝓼",
        t: "𝓽",
        u: "𝓾",
        v: "𝓿",
        w: "𝔀",
        x: "𝔁",
        y: "𝔂",
        z: "𝔃",
      },
      DOUBLE_double: {
        /* mapping for double */
        a: "𝕒",
        b: "𝕓",
        c: "𝕔",
        d: "𝕕",
        e: "𝕖",
        f: "𝕗",
        g: "𝕘",
        h: "𝕙",
        i: "𝕚",
        j: "𝕛",
        k: "𝕜",
        l: "𝕝",
        m: "𝕞",
        n: "𝕟",
        o: "𝕠",
        p: "𝕡",
        q: "𝕢",
        r: "𝕣",
        s: "𝕤",
        t: "𝕥",
        u: "𝕦",
        v: "𝕧",
        w: "𝕨",
        x: "𝕩",
        y: "𝕪",
        z: "𝕫",
      },
      GOTHIC_gothic: {
        /* mapping for gothic */
        A: "𝔄",
        B: "𝔅",
        C: "ℭ",
        D: "𝔇",
        E: "𝔈",
        F: "𝔉",
        G: "𝔊",
        H: "ℌ",
        I: "ℑ",
        J: "𝔍",
        K: "𝔎",
        L: "𝔏",
        M: "𝔐",
        N: "𝔑",
        O: "𝔒",
        P: "𝔓",
        Q: "𝔔",
        R: "ℜ",
        S: "𝔖",
        T: "𝔗",
        U: "𝔘",
        V: "𝔙",
        W: "𝔚",
        X: "𝔛",
        Y: "𝔜",
        Z: "ℨ",
        a: "𝔞",
        b: "𝔟",
        c: "𝔠",
        d: "𝔡",
        e: "𝔢",
        f: "𝔣",
        g: "𝔤",
        h: "𝔥",
        i: "𝔦",
        j: "𝔧",
        k: "𝔨",
        l: "𝔩",
        m: "𝔪",
        n: "𝔫",
        o: "𝔬",
        p: "𝔭",
        q: "𝔮",
        r: "𝔯",
        s: "𝔰",
        t: "𝔱",
        u: "𝔲",
        v: "𝔳",
        w: "𝔴",
        x: "𝔵",
        y: "𝔶",
        z: "𝔷",
      },
      MONOSPACE_monospace: {
        /* mapping for monospace */
        A: "𝙰",
        B: "𝙱",
        C: "𝙲",
        D: "𝙳",
        E: "𝙴",
        F: "𝙵",
        G: "𝙶",
        H: "𝙷",
        I: "𝙸",
        J: "𝙹",
        K: "𝙺",
        L: "𝙻",
        M: "𝙼",
        N: "𝙽",
        O: "𝙾",
        P: "𝙿",
        Q: "𝚀",
        R: "𝚁",
        S: "𝚂",
        T: "𝚃",
        U: "𝚄",
        V: "𝚅",
        W: "𝚆",
        X: "𝚇",
        Y: "𝚈",
        Z: "𝚉",
        a: "𝚊",
        b: "𝚋",
        c: "𝚌",
        d: "𝚍",
        e: "𝚎",
        f: "𝚏",
        g: "𝚐",
        h: "𝚑",
        i: "𝚒",
        j: "𝚓",
        k: "𝚔",
        l: "𝚕",
        m: "𝚖",
        n: "𝚗",
        o: "𝚘",
        p: "𝚙",
        q: "𝚚",
        r: "𝚛",
        s: "𝚜",
        t: "𝚝",
        u: "𝚞",
        v: "𝚟",
        w: "𝚠",
        x: "𝚡",
        y: "𝚢",
        z: "𝚣",
      },
      SANS_BOLD_sansBold: {
        /* mapping for sansBold */
        A: "𝗔",
        B: "𝗕",
        C: "𝗖",
        D: "𝗗",
        E: "𝗘",
        F: "𝗙",
        G: "𝗚",
        H: "𝗛",
        I: "𝗜",
        J: "𝗝",
        K: "𝗞",
        L: "𝗟",
        M: "𝗠",
        N: "𝗡",
        O: "𝗢",
        P: "𝗣",
        Q: "𝗤",
        R: "𝗥",
        S: "𝗦",
        T: "𝗧",
        U: "𝗨",
        V: "𝗩",
        W: "𝗪",
        X: "𝗫",
        Y: "𝗬",
        Z: "𝗭",
        a: "𝗮",
        b: "𝗯",
        c: "𝗰",
        d: "𝗱",
        e: "𝗲",
        f: "𝗳",
        g: "𝗴",
        h: "𝗵",
        i: "𝗶",
        j: "𝗷",
        k: "𝗸",
        l: "𝗹",
        m: "𝗺",
        n: "𝗻",
        o: "𝗼",
        p: "𝗽",
        q: "𝗾",
        r: "𝗿",
        s: "𝘀",
        t: "𝘁",
        u: "𝘂",
        v: "𝘃",
        w: "𝘄",
        x: "𝘅",
        y: "𝘆",
        z: "𝘇",
      },
      SANS_ITALIC_sansItalic: {
        /* mapping for sansItalic */
        A: "𝘈",
        B: "𝘉",
        C: "𝘊",
        D: "𝘋",
        E: "𝘌",
        F: "𝘍",
        G: "𝘎",
        H: "𝘏",
        I: "𝘐",
        J: "𝘉",
        K: "𝘒",
        L: "𝘓",
        M: "𝘔",
        N: "𝘕",
        O: "𝘖",
        P: "𝘗",
        Q: "𝘘",
        R: "𝘙",
        S: "𝘚",
        T: "𝘛",
        U: "𝘜",
        V: "𝘝",
        W: "𝘞",
        X: "𝘟",
        Y: "𝘠",
        Z: "𝘡",
        a: "𝘢",
        b: "𝘣",
        c: "𝘤",
        d: "𝘥",
        e: "𝘦",
        f: "𝘧",
        g: "𝘨",
        h: "𝘩",
        i: "𝘪",
        j: "𝘫",
        k: "𝘬",
        l: "𝘭",
        m: "𝘮",
        n: "𝘯",
        o: "𝘰",
        p: "𝘱",
        q: "𝘲",
        r: "𝘳",
        s: "𝘴",
        t: "𝘵",
        u: "𝘶",
        v: "𝘷",
        w: "𝘸",
        x: "𝘹",
        y: "𝘺",
        z: "𝘻",
      },
      SANSBOLDITALIC_sansBoldItalic: {
        /* mapping for sansBoldItalic */
        A: "𝙄",
        B: "𝙅",
        C: "𝙆",
        D: "𝙇",
        E: "𝙈",
        F: "𝙉",
        G: "𝙊",
        H: "𝙋",
        I: "𝙌",
        J: "𝙍",
        K: "𝙎",
        L: "𝙏",
        M: "𝙐",
        N: "𝙑",
        O: "𝙒",
        P: "𝙓",
        Q: "𝙔",
        R: "𝙕",
        S: "𝙖",
        T: "𝙗",
        U: "𝙘",
        V: "𝙙",
        W: "𝙚",
        X: "𝙛",
        Y: "𝙜",
        Z: "𝙝",
        a: "𝙞",
        b: "𝙟",
        c: "𝙠",
        d: "𝙡",
        e: "𝙢",
        f: "𝙣",
        g: "𝙤",
        h: "𝙥",
        i: "𝙦",
        j: "𝙧",
        k: "𝙨",
        l: "𝙩",
        m: "𝙪",
        n: "𝙫",
        o: "𝙬",
        p: "𝙭",
        q: "𝙮",
        r: "𝙯",
        s: "𝙰",
        t: "𝙱",
        u: "𝙲",
        v: "𝙳",
        w: "𝙴",
        x: "𝙵",
        y: "𝙶",
        z: "𝙷",
      },
      SMALLCAPS_smallCaps: {
        /* mapping for smallCaps */
        A: "A",
        B: "B",
        C: "C",
        D: "D",
        E: "E",
        F: "F",
        G: "G",
        H: "H",
        I: "I",
        J: "J",
        K: "K",
        L: "L",
        M: "M",
        N: "N",
        O: "O",
        P: "P",
        Q: "Q",
        R: "R",
        S: "S",
        T: "T",
        U: "U",
        V: "V",
        W: "W",
        X: "X",
        Y: "Y",
        Z: "Z",
        a: "ᴀ",
        b: "ʙ",
        c: "ᴄ",
        d: "ᴅ",
        e: "ᴇ",
        f: "ꜰ",
        g: "ɢ",
        h: "ʜ",
        i: "ɪ",
        j: "ᴊ",
        k: "ᴋ",
        l: "ʟ",
        m: "ᴍ",
        n: "ɴ",
        o: "ᴏ",
        p: "ᴘ",
        q: "q",
        r: "ʀ",
        s: "s",
        t: "ᴛ",
        u: "ᴜ",
        v: "ᴠ",
        w: "ᴡ",
        x: "x",
        y: "ʏ",
        z: "ᴢ",
      },
      CIRCLED_circled: {
        /* mapping for circled */
        A: "Ⓐ",
        B: "Ⓑ",
        C: "Ⓒ",
        D: "Ⓓ",
        E: "Ⓔ",
        F: "Ⓕ",
        G: "Ⓖ",
        H: "Ⓗ",
        I: "Ⓘ",
        J: "Ⓙ",
        K: "Ⓚ",
        L: "Ⓛ",
        M: "Ⓜ",
        N: "Ⓝ",
        O: "Ⓞ",
        P: "Ⓟ",
        Q: "Ⓠ",
        R: "Ⓡ",
        S: "Ⓢ",
        T: "Ⓣ",
        U: "Ⓤ",
        V: "Ⓥ",
        W: "Ⓦ",
        X: "Ⓧ",
        Y: "Ⓨ",
        Z: "Ⓩ",
        a: "ⓐ",
        b: "ⓑ",
        c: "ⓒ",
        d: "ⓓ",
        e: "ⓔ",
        f: "ⓕ",
        g: "ⓖ",
        h: "ⓗ",
        i: "ⓘ",
        j: "ⓙ",
        k: "ⓚ",
        l: "ⓛ",
        m: "ⓜ",
        n: "ⓝ",
        o: "ⓞ",
        p: "ⓟ",
        q: "ⓠ",
        r: "ⓡ",
        s: "ⓢ",
        t: "ⓣ",
        u: "ⓤ",
        v: "ⓥ",
        w: "ⓦ",
        x: "ⓧ",
        y: "ⓨ",
        z: "ⓩ",
      },
      SQUARED_squared: {
        /* mapping for squared */
        A: "🄰",
        B: "🄱",
        C: "🄲",
        D: "🄳",
        E: "🄴",
        F: "🄵",
        G: "🄶",
        H: "🄷",
        I: "🄸",
        J: "🄹",
        K: "🄺",
        L: "🄻",
        M: "🄼",
        N: "🄽",
        O: "🄾",
        P: "🄿",
        Q: "🅀",
        R: "🅁",
        S: "🅂",
        T: "🅃",
        U: "🅄",
        V: "🅅",
        W: "🅆",
        X: "🅇",
        Y: "🅈",
        Z: "🅉",
        a: "🅰",
        b: "🅱",
        c: "🅲",
        d: "🅳",
        e: "🅴",
        f: "🅵",
        g: "🅶",
        h: "🅷",
        i: "🅸",
        j: "🅹",
        k: "🅺",
        l: "🅻",
        m: "🅼",
        n: "🅽",
        o: "🅾",
        p: "🅿",
        q: "🆀",
        r: "🆁",
        s: "🆂",
        t: "🆃",
        u: "🆄",
        v: "🆅",
        w: "🆆",
        x: "🆇",
        y: "🆈",
        z: "🆉",
      },
      FANCY_fancy: {
        /* mapping for fancy */
        A: "𝒜",
        B: "ℬ",
        C: "𝒞",
        D: "𝒟",
        E: "ℰ",
        F: "ℱ",
        G: "𝒢",
        H: "ℋ",
        I: "ℐ",
        J: "𝒥",
        K: "𝒦",
        L: "ℒ",
        M: "ℳ",
        N: "𝒩",
        O: "𝒪",
        P: "𝒫",
        Q: "𝒬",
        R: "𝒭",
        S: "𝒮",
        T: "𝒯",
        U: "𝒰",
        V: "𝒱",
        W: "𝒲",
        X: "𝒳",
        Y: "𝒴",
        Z: "𝒵",
        a: "𝒶",
        b: "𝒷",
        c: "𝒸",
        d: "𝒹",
        e: "ℯ",
        f: "𝒻",
        g: "ℊ",
        h: "𝒽",
        i: "𝒾",
        j: "𝒿",
        k: "𝓀",
        l: "𝓁",
        m: "𝓂",
        n: "𝓃",
        o: "ℴ",
        p: "𝓅",
        q: "𝓆",
        r: "𝓇",
        s: "𝓈",
        t: "𝓉",
        u: "𝓊",
        v: "𝓋",
        w: "𝓌",
        x: "𝓍",
        y: "𝓎",
        z: "𝓏",
      },
      RETRO_retro: {
        /* mapping for retro */
        A: "ᗩ",
        B: "ᗷ",
        C: "ᑕ",
        D: "ᗪ",
        E: "E",
        F: "ᖴ",
        G: "G",
        H: "ᕼ",
        I: "I",
        J: "ᒍ",
        K: "K",
        L: "ᒪ",
        M: "M",
        N: "ᘉ",
        O: "O",
        P: "ᑭ",
        Q: "Q",
        R: "ᖇ",
        S: "S",
        T: "T",
        U: "ᑌ",
        V: "V",
        W: "W",
        X: "X",
        Y: "Y",
        Z: "Z",
        a: "ᗩ",
        b: "ᗷ",
        c: "ᑕ",
        d: "ᗪ",
        e: "e",
        f: "ᖴ",
        g: "g",
        h: "ᕼ",
        i: "i",
        j: "ᒍ",
        k: "k",
        l: "ᒪ",
        m: "m",
        n: "ᘉ",
        o: "o",
        p: "ᑭ",
        q: "q",
        r: "ᖇ",
        s: "s",
        t: "t",
        u: "ᑌ",
        v: "v",
        w: "w",
        x: "x",
        y: "y",
        z: "z",
      },
      CUSTOM1: {
        // 𝔔𝔚𝔈ℜ𝔗𝔜𝔘ℑ𝔒𝔓𝔄𝔖𝔇𝔉𝔊ℌ𝔍𝔎𝔏ℨ𝔛ℭ𝔙𝔅𝔑𝔐
        Q: "𝔔",
        W: "𝔚",
        E: "𝔈",
        R: "ℜ",
        T: "𝔗",
        Y: "𝔜",
        U: "𝔘",
        I: "ℑ",
        O: "𝔒",
        P: "𝔓",
        A: "𝔄",
        S: "𝔖",
        D: "𝔇",
        F: "𝔉",
        G: "𝔊",
        H: "ℌ",
        J: "𝔍",
        K: "𝔎",
        L: "𝔏",
        Z: "ℨ",
        X: "𝔛",
        C: "ℭ",
        V: "𝔙",
        B: "𝔅",
        N: "𝔑",
        M: "𝔐",
      },
      CUSTOM2: {
        // 𝒬𝒲𝐸𝑅𝒯𝒴𝒰𝐼𝒪𝒫𝒜𝒮𝒟𝐹𝒢𝐻𝒥𝒦𝐿𝒵𝒳𝒞𝒱𝐵𝒩𝑀
        Q: "𝒬",
        W: "𝒲",
        E: "𝐸",
        R: "𝑅",
        T: "𝒯",
        Y: "𝒴",
        U: "𝒰",
        I: "𝐼",
        O: "𝒪",
        P: "𝒫",
        A: "𝒜",
        S: "𝒮",
        D: "𝒟",
        F: "𝐹",
        G: "𝒢",
        H: "𝐻",
        J: "𝒥",
        K: "𝒦",
        L: "𝐿",
        Z: "𝒵",
        X: "𝒳",
        C: "𝒞",
        V: "𝒱",
        B: "𝐵",
        N: "𝒩",
        M: "𝑀",
      },
      CUSTOM3: {
        // Q⃣   W⃣   E⃣   R⃣   T⃣   Y⃣   U⃣   I⃣   O⃣   P⃣   A⃣   S⃣   D⃣   F⃣   G⃣   H⃣   J⃣   K⃣   L⃣   Z⃣   X⃣   C⃣   V⃣   B⃣   N⃣   M⃣
        Q: "Q⃣",
        W: "W⃣",
        E: "E⃣",
        R: "R⃣",
        T: "T⃣",
        Y: "Y⃣",
        U: "U⃣",
        I: "I⃣",
        O: "O⃣",
        P: "P⃣",
        A: "A⃣",
        S: "S⃣",
        D: "D⃣",
        F: "F⃣",
        G: "G⃣",
        H: "H⃣",
        J: "J⃣",
        K: "K⃣",
        L: "L⃣",
        Z: "Z⃣",
        X: "X⃣",
        C: "C⃣",
        V: "V⃣",
        B: "B⃣",
        N: "N⃣",
        M: "M⃣",
      },
      CUSTOM4: {
        // Q₩ɆⱤ₮ɎɄłØ₱₳₴Đ₣₲ⱧJ₭ⱠⱫӾ₵V฿₦₥
        Q: "Q",
        W: "₩",
        E: "Ɇ",
        R: "Ɽ",
        T: "₮",
        Y: "Ɏ",
        U: "Ʉ",
        I: "ł",
        O: "Ø",
        P: "₱",
        A: "₳",
        S: "₴",
        D: "Đ",
        F: "₣",
        G: "₲",
        H: "Ⱨ",
        J: "J",
        K: "₭",
        L: "Ⱡ",
        Z: "Ⱬ",
        X: "Ӿ",
        C: "₵",
        V: "V",
        B: "฿",
        N: "₦",
        M: "₥",
      },
      CUSTOM5: {
        // Ɋ山乇尺ㄒㄚㄩ丨ㄖ卩卂丂ᗪ千Ꮆ卄ﾌҜㄥ乙乂匚ᐯ乃几爪
        Q: "Ɋ",
        W: "山",
        E: "乇",
        R: "尺",
        T: "ㄒ",
        Y: "ㄚ",
        U: "ㄩ",
        I: "丨",
        O: "ㄖ",
        P: "卩",
        A: "卂",
        S: "丂",
        D: "ᗪ",
        F: "千",
        G: "Ꮆ",
        H: "卄",
        J: "ﾌ",
        K: "Ҝ",
        L: "ㄥ",
        Z: "乙",
        X: "乂",
        C: "匚",
        V: "ᐯ",
        B: "乃",
        N: "几",
        M: "爪",
      },
      CUSTOM6: {
        // 【Q】【W】【E】【R】【T】【Y】【U】【I】【O】【P】【A】【S】【D】【F】【G】【H】【J】【K】【L】【Z】【X】【C】【V】【B】【N】【M】
        Q: "【Q】",
        W: "【W】",
        E: "【E】",
        R: "【R】",
        T: "【T】",
        Y: "【Y】",
        U: "【U】",
        I: "【I】",
        O: "【O】",
        P: "【P】",
        A: "【A】",
        S: "【S】",
        D: "【D】",
        F: "【F】",
        G: "【G】",
        H: "【H】",
        J: "【J】",
        K: "【K】",
        L: "【L】",
        Z: "【Z】",
        X: "【X】",
        C: "【C】",
        V: "【V】",
        B: "【B】",
        N: "【N】",
        M: "【M】",
      },
      CUSTOM7: {
        // 『Q』『W』『E』『R』『T』『Y』『U』『I』『O』『P』『A』『S』『D』『F』『G』『H』『J』『K』『L』『Z』『X』『C』『V』『B』『N』『M』
        Q: "『Q』",
        W: "『W』",
        E: "『E』",
        R: "『R』",
        T: "『T』",
        Y: "『Y』",
        U: "『U』",
        I: "『I』",
        O: "『O』",
        P: "『P』",
        A: "『A』",
        S: "『S』",
        D: "『D』",
        F: "『F』",
        G: "『G』",
        H: "『H』",
        J: "『J』",
        K: "『K』",
        L: "『L』",
        Z: "『Z』",
        X: "『X』",
        C: "『C』",
        V: "『V』",
        B: "『B』",
        N: "『N』",
        M: "『M』",
      },
      CUSTOM8: {
        // [̲̅Q][̲̅W][̲̅E][̲̅R][̲̅T][̲̅Y][̲̅U][̲̅I][̲̅O][̲̅P][̲̅A][̲̅S][̲̅D][̲̅F][̲̅G][̲̅H][̲̅J][̲̅K][̲̅L][̲̅Z][̲̅X][̲̅C][̲̅V][̲̅B][̲̅N][̲̅M]
        Q: "[̲̅Q]",
        W: "[̲̅W]",
        E: "[̲̅E]",
        R: "[̲̅R]",
        T: "[̲̅T]",
        Y: "[̲̅Y]",
        U: "[̲̅U]",
        I: "[̲̅I]",
        O: "[̲̅O]",
        P: "[̲̅P]",
        A: "[̲̅A]",
        S: "[̲̅S]",
        D: "[̲̅D]",
        F: "[̲̅F]",
        G: "[̲̅G]",
        H: "[̲̅H]",
        J: "[̲̅J]",
        K: "[̲̅K]",
        L: "[̲̅L]",
        Z: "[̲̅Z]",
        X: "[̲̅X]",
        C: "[̲̅C]",
        V: "[̲̅V]",
        B: "[̲̅B]",
        N: "[̲̅N]",
        M: "[̲̅M]",
      },
      CUSTOM9: {
        // Q̲W̲E̲R̲T̲Y̲U̲I̲O̲P̲A̲S̲D̲F̲G̲H̲J̲K̲L̲Z̲X̲C̲V̲B̲N̲M̲
        Q: "Q̲",
        W: "W̲",
        E: "E̲",
        R: "R̲",
        T: "T̲",
        Y: "Y̲",
        U: "U̲",
        I: "I̲",
        O: "O̲",
        P: "P̲",
        A: "A̲",
        S: "S̲",
        D: "D̲",
        F: "F̲",
        G: "G̲",
        H: "H̲",
        J: "J̲",
        K: "K̲",
        L: "L̲",
        Z: "Z̲",
        X: "X̲",
        C: "C̲",
        V: "V̲",
        B: "B̲",
        N: "N̲",
        M: "M̲",
      },
      CUSTOM10: {
        // Q͎W͎E͎R͎T͎Y͎U͎I͎O͎P͎A͎S͎D͎F͎G͎H͎J͎K͎L͎Z͎X͎C͎V͎B͎N͎M͎
        Q: "Q͎",
        W: "W͎",
        E: "E͎",
        R: "R͎",
        T: "T͎",
        Y: "Y͎",
        U: "U͎",
        I: "I͎",
        O: "O͎",
        P: "P͎",
        A: "A͎",
        S: "S͎",
        D: "D͎",
        F: "F͎",
        G: "G͎",
        H: "H͎",
        J: "J͎",
        K: "K͎",
        L: "L͎",
        Z: "Z͎",
        X: "X͎",
        C: "C͎",
        V: "V͎",
        B: "B͎",
        N: "N͎",
        M: "M͎",
      },
      CUSTOM11: {
        // Q͓̽W͓̽E͓̽R͓̽T͓̽Y͓̽U͓̽I͓̽O͓̽P͓̽A͓̽S͓̽D͓̽F͓̽G͓̽H͓̽J͓̽K͓̽L͓̽Z͓̽X͓̽C͓̽V͓̽B͓̽N͓̽M͓̽
        Q: "Q͓̽",
        W: "W͓̽",
        E: "E͓̽",
        R: "R͓̽",
        T: "T͓̽",
        Y: "Y͓̽",
        U: "U͓̽",
        I: "I͓̽",
        O: "O͓̽",
        P: "P͓̽",
        A: "A͓̽",
        S: "S͓̽",
        D: "D͓̽",
        F: "F͓̽",
        G: "G͓̽",
        H: "H͓̽",
        J: "J͓̽",
        K: "K͓̽",
        L: "L͓̽",
        Z: "Z͓̽",
        X: "X͓̽",
        C: "C͓̽",
        V: "V͓̽",
        B: "B͓̽",
        N: "N͓̽",
        M: "M͓̽",
      },
    }),
    [],
  );
  const initialState: FontState = {
    isHidden: false,
    inputText: "",
    selectedFont: "sans",
    copied: "",
    convertedText: "",
  };
  const [state, dispatch] = useReducer(fontReducer, initialState);
  const { isHidden, inputText, selectedFont, copied, convertedText } = state;
  const convertText = useCallback((text: string, style: string, map: FontMap): string => {
    return convertTextHelper(text, style, map);
  }, []);
  const currencySymbols = useMemo(
    () => [
      "$",
      "¥",
      "฿",
      "₫",
      "₩",
      "֏",
      "€",
      "₹",
      "₪",
      "₺",
      "₡",
      "₦",
      "£",
      "₽",
      "₢",
      "₱",
      "৳",
      "₲",
      "₮",
      "₸",
      "₾",
      "₥",
      "៛",
      "₨",
      "₴",
      "₵",
      "₭",
      "؋",
      "૱",
      "¢",
      "﷼",
      "₣",
      "₿",
      "₼",
      "௹",
      "¤",
      "⃀",
      "₻",
      "ƒ",
      "₧",
      "৲",
      "₳",
      "₯",
      "₤",
      "₷",
      "৹",
      "₰",
      "₠",
      "ℳ",
      "₶",
      "৻",
    ],
    [],
  );
  const customEmoticons = useMemo(
    () => [
      "⚆_⚆",
      "o_o",
      "◉_◉",
      "(•_•)",
      "(•ˋ _ ˊ•)",
      "(⊙_◎)",
      "(⊙ˍ⊙)",
      "(●__●)",
      "(⓿_⓿)",
      "(o|o)",
      "(。_。)",
      "(￣_,￣ )",
      "(¬_¬ )",
      "( ͡• ͜ʖ ͡• )",
      "( ͡° ͜ʖ ͡°)",
      "(￣︿￣)",
      "( ˘︹˘ )",
      "(ಥ_ಥ)",
      "(ಥ﹏ಥ)",
      "＞﹏＜",
      "{{{(>_<)}}}",
      "(╰（‵□′）╯)",
      "(ಠ▃ಠ)",
      "(ಠ_ಠ)",
      "(ಠಿ_ಠ)",
      "(ಠ﹏ಠ)",
      "( ͡ಠ ʖ̯ ͡ಠ)",
      "( ఠ ͟ʖ ఠ)",
      "(✿◠‿◠)",
      "（︶^︶）",
      "(^人^)",
      "¯\\(ツ)_/¯",
      "¯\\_( ͡° ͜ʖ ͡°)_/¯",
      "(►__◄)",
      "( ﾉ ﾟｰﾟ)ﾉ",
      "＼(ﾟｰﾟ＼)",
      "(•_•)",
      "/ᐠ｡ꞈ｡ᐟ\\",
      "♨︎_♨︎",
      "←_←",
      "→_→",
      "(◎﹏◎)",
      "(○|￣|_)",
      "(○|￣|_=3)",
      "¯\\(°_o)/¯",
    ],
    [],
  );
  const geometricSymbols = useMemo(
    () => [
      "←",
      "→",
      "↖",
      "↗",
      "↜",
      "↟",
      "↑",
      "↔",
      "↙",
      "↘",
      "↝",
      "↡",
      "↓",
      "↕",
      "↚",
      "↛",
      "↞",
      "↠",
      "↢",
      "↣",
      "↨",
      "↭",
      "↮",
      "↯",
      "↤",
      "↦",
      "↩",
      "↪",
      "↰",
      "↱",
      "↥",
      "↧",
      "↫",
      "↬",
      "↲",
      "↳",
      "↴",
      "↺",
      "↸",
      "↹",
      "⇦",
      "⇨",
      "⇘",
      "⇗",
      "⇱",
      "⇲",
      "▢",
      "▥",
      "▬",
      "▨",
      "▭",
      "▮",
      "▯",
      "▩",
      "▦",
      "▣",
      "▤",
      "▧",
      "◊",
      "▪",
      "▫",
      "▰",
      "▱",
      "◀",
      "▶",
      "◁",
      "▷",
      "▲",
      "△",
      "◄",
      "►",
      "◅",
      "▻",
      "◆",
      "◇",
      "◈",
      "◌",
      "●",
      "◙",
      "▼",
      "▽",
      "○",
      "◍",
      "◓",
      "◚",
      "▾",
      "▿",
      "◉",
      "◎",
      "◒",
      "◛",
      "◤",
      "◣",
      "◢",
      "◥",
      "◝",
      "◞",
      "◟",
      "◜",
      "◖",
      "◗",
      "◐",
      "◑",
      "◠",
      "◡",
      "◔",
      "◕",
      "◧",
      "◨",
      "◲",
      "◱",
      "◶",
      "◵",
      "◸",
      "◹",
      "◳",
      "◰",
      "◷",
      "◴",
      "◺",
      "◿",
      "◫",
      "⊟",
      "◯",
      "◬",
      "◭",
      "◮",
      "⌜",
      "⌝",
      "⌏",
      "⌎",
      "◘",
      "⌞",
      "⌟",
      "⌍",
      "⌌",
      "◩",
      "■",
      "◻",
      "■",
      "□",
      "◪",
    ],
    [],
  );
  const generalSymbols = useMemo(
    () => [
      "§",
      "℃",
      "℉",
      "¦",
      "№",
      "™",
      "⁅",
      "⁆",
      "><",
      "⌈",
      "⌉",
      "⌋",
      "⌊",
      "›",
      "‹",
      "»",
      "«",
      "`",
      "´",
      "‸",
      "¸",
      "¯",
      "¨",
      "‡",
      "†",
      "⁗",
      "‷",
      "‴",
      "•",
      "‣",
      "⁌",
      "⁍",
      "⁑",
      "⁜",
      "※",
      "⁂",
      "⁾",
      "⁽",
      "♪",
      "%",
      "‰",
      "‱",
      "·",
      "․",
      "⁞",
      "⁛",
      "¬",
      "‥",
      "⁚",
      "⁖",
      "⁙",
      "✓",
      ":",
      "…",
      "⁝",
      "⁘",
      "_",
      "✕",
      "‼",
      "°",
      "⁔",
      "⁀",
      "¿",
      "⁈",
      "ª",
      "‿",
      "⁐",
      "‽",
      "⸘",
      "⁇",
      "⁁",
      "⌀",
      "⌁",
      "⏖",
      "⏔",
      "⏕",
    ],
    [],
  );
  const fontOptions = useMemo(
    () =>
      Object.keys(fontMap).map((style) => {
        // تبدیل نام استایل به فرمت قابل نمایش (مثلاً sansBold -> Sans Bold)
        const displayName = style
          .replace(/([A-Z])/g, " $1") // اضافه کردن فاصله قبل از حروف بزرگ
          .replace(/^./, (str) => str.toUpperCase()) // بزرگ کردن حرف اول
          .trim();

        return (
          <div key={style} id={style}>
            {convertText(displayName, style, fontMap)}
          </div>
        );
      }),
    [fontMap, convertText],
  );
  useEffect(() => {
    const newConvertedText = convertText(inputText, selectedFont, fontMap);
    dispatch({ type: "SET_CONVERTED_TEXT", payload: newConvertedText });
  }, [inputText, selectedFont, fontMap, convertText]);

  const copyToClipboard = useCallback(async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      dispatch({ type: "SET_COPIED", payload: text });
      setTimeout(() => dispatch({ type: "RESET_COPIED" }), 2000);
    } catch (err) {
      console.error("Failed to copy text:", err);
    }
  }, []);

  const handleInputChange = useCallback((e: ChangeEvent<HTMLTextAreaElement>) => {
    dispatch({ type: "SET_INPUT_TEXT", payload: e.target.value });
  }, []);

  const handleFontSelect = useCallback((id: string) => {
    dispatch({ type: "SET_SELECTED_FONT", payload: id });
  }, []);

  const toggleHidden = useCallback(() => {
    dispatch({ type: "TOGGLE_HIDDEN" });
  }, []);

  const appendSymbol = useCallback(
    (symbol: string) => {
      dispatch({ type: "SET_INPUT_TEXT", payload: inputText + symbol });
    },
    [inputText],
  );
  const SymbolPool = useCallback(
    ({ title, symbols }: { title: string; symbols: string[] }) => (
      <div className="headerandinput">
        <div className="headertext">{title}</div>
        <div className={styles.symbolpool}>
          {symbols.map((symbol, idx) => (
            <div key={idx} className={styles.symbolicon} onClick={() => appendSymbol(symbol)}>
              {symbol}
            </div>
          ))}
        </div>
      </div>
    ),
    [appendSymbol],
  );

  return (
    <>
      <div className="tooBigCard" style={{ gridRowEnd: isHidden ? "span 10" : "span 82" }}>
        <div className="headerChild" onClick={toggleHidden}>
          <div className="circle"></div>
          <div className="Title">{t(LanguageKey.pageTools_CustomFont)}</div>
        </div>
        <main className={`${styles.all} ${isHidden ? "" : styles.show}`}>
          {!hasAccess && <NotAllowedCard />}
          {hasAccess && (
            <>
              <DragDrop data={fontOptions} handleOptionSelect={handleFontSelect} />
              <TextArea
                className="captiontextarea"
                placeHolder={t(LanguageKey.EnterYourText)}
                value={convertedText}
                handleInputChange={handleInputChange}
                role={"textbox"}
                title={"Type your text here"}
                style={{ height: "200px", fontSize: "16px" }}
                id="customFontInput"
                name="customFontInput"
              />
              <div className={`${styles.symbolpoollistparent} translate`}>
                <SymbolPool title="Custom Emoticons" symbols={customEmoticons} />
                <SymbolPool title="General Symbols" symbols={generalSymbols} />
                <SymbolPool title="Currency Symbols" symbols={currencySymbols} />
                <SymbolPool title="Geometric Symbols" symbols={geometricSymbols} />
              </div>
              <button
                style={{ minHeight: "48px" }}
                onClick={() => copyToClipboard(convertedText)}
                className={convertedText.trim() === "" ? "disableButton" : "saveButton"}
                disabled={convertedText.trim() === ""}>
                {convertedText.trim() === ""
                  ? t(LanguageKey.CopyText)
                  : copied === convertedText
                    ? t(LanguageKey.successfulCopy)
                    : t(LanguageKey.CopyText)}
              </button>
            </>
          )}
        </main>
      </div>
    </>
  );
}
