import { t } from "i18next";
import { LanguageKey } from "saeed/i18n";

export enum BusinessDay {
  Monday = 0,
  Tuesday = 1,
  Wednesday = 2,
  Thursday = 3,
  Friday = 4,
  Saturday = 5,
  Sunday = 6,
}
export enum FeatureType {
  FeaturesBox = 0,
  Reviews = 1,
  Announcements = 2,
  OnlineStream = 3,
  LastVideo = 4,
  Products = 5,
  AdsTimeline = 6,
  QandABox = 7,
  LinkShortcut = 8,
  ContactAndMap = 9,
  Banner = 10,
}
export enum PriceType {
  Dollar = 0,
  Rial = 1,
  Toman = 2,
}
export enum PriceFormaterClassName {
  PostPrice = "postprice",
  PostPriceRed = "postpricered",
  PostPriceBlue = "postpriceblue",
}
export enum AdsType {
  CampaignAd,
  PostAd,
  StoryAd,
}

export enum BannerType {
  Base64 = 0,
  Url = 1,
}
export const FeatureName = {
  Banner: t(LanguageKey.marketPropertiesBanner),
  FeaturesBox: t(LanguageKey.marketPropertiesFeaturesBox),
  Reviews: t(LanguageKey.marketPropertiesReviews),
  Announcements: t(LanguageKey.marketPropertiesAnnouncements),
  OnlineStream: t(LanguageKey.marketPropertiesOnlineStream),
  LastVideo: t(LanguageKey.marketPropertiesLastVideo),
  Products: t(LanguageKey.marketPropertiesProducts),
  AdsTimeline: t(LanguageKey.marketPropertiesAdsTimeline),
  QandABox: t(LanguageKey.marketPropertiesQandABox),
  LinkShortcut: t(LanguageKey.marketPropertiesLinkShortcut),
  ContactAndMap: t(LanguageKey.marketPropertiesContactAndMap),
};

// export enum FeatureName {
//   Banner = "Banner",
//   FeaturesBox = "features box",
//   Reviews = "reviews",
//   Announcements = "Announcements",
//   OnlineStream = "Online Stream",
//   LastVideo = "your last video",
//   Products = "Products",
//   AdsTimeline = "Ads timeline",
//   QandABox = "Q & A Boxes",
//   LinkShortcut = "Link Shortcuts",
//   ContactAndMap = "Contact & Map",
// }

export enum TitleName {
  Custome = "Custome",
  GeneralLink = "General Link",
  PDFLink = "PDF Link",
  Contact = "Contact",
  RSSFeed = "RSS Feed",
  Instagram = "Instagram",
  ClubHouse = "Club House",
  Skype = "Skype",
  WhatsApp = "WhatsApp",
  Twitter = "Twitter",
  Dribbble = "Dribbble",
  Snapchat = "Snapchat",
  Pinterest = "Pinterest",
  Telegram = "Telegram",
  Facebook = "Facebook",
  Behance = "Behance",
  MetaMessenger = "Meta Messenger",
  Ticktok = "Ticktok",
  Linkedin = "Linkedin",
  x = "X",
  AppleMusic = "Apple Music",
  AmazonMusic = "Amazon Music",
  SoundCloud = "SoundCloud",
  Spotify = "Spotify",
  Aparat = "Aparat",
  twitch = "twitch",
  YouTube = "YouTube",
  Shazam = "Shazam",
  Discord = "Discord",
  vimeo = "vimeo",
  RadioJavan = "Radio Javan",
  Dropbox = "Dropbox",
  Mega = "Mega",
  IclouadDrive = "iCloud Drive",
  GoogleDrive = "Google Drive",
  MediaFire = "MediaFire",
  OneDrive = "OneDrive",
  PayPal = "PayPal",
  Square = " Square",
  Venmo = "Venmo",
  VisaCard = "VisaCard",
  TipJar = "TipJar",
  ZarinPal = "ZarinPal",
  AsanPardakht = "AsanPardakht",
  Zibal = "Zibal",
  Payir = "Pay.ir",
  NextPay = "NextPay",
  IDPay = "IDPay",
}
export enum TitleType {
  Custome = -1,
  GeneralLink = 0,
  PDFLink = 1,
  Contact = 2,
  RSSFeed = 3,
  Instagram = 4,
  ClubHouse = 5,
  Skype = 6,
  WhatsApp = 7,
  Twitter = 8,
  Dribbble = 9,
  Snapchat = 10,
  Pinterest = 11,
  Telegram = 12,
  Facebook = 13,
  Behance = 14,
  MetaMessenger = 15,
  Ticktok = 16,
  Linkedin = 17,
  x = 18,
  AppleMusic = 19,
  AmazonMusic = 20,
  SoundCloud = 21,
  Spotify = 22,
  Aparat = 23,
  twitch = 24,
  YouTube = 25,
  Shazam = 26,
  Discord = 27,
  vimeo = 28,
  RadioJavan = 29,
  Dropbox = 30,
  Mega = 31,
  IclouadDrive = 32,
  GoogleDrive = 33,
  MediaFire = 34,
  OneDrive = 35,
  PayPal = 36,
  Square = 37,
  Venmo = 38,
  VisaCard = 39,
  TipJar = 40,
  ZarinPal = 41,
  AsanPardakht = 42,
  Zibal = 43,
  Payir = 44,
  NextPay = 45,
  IDPay = 46,
}
export enum CategorySection {
  Entertaimet = 0,
  Game = 1,
  Fashion = 2,
}
export enum MarketType {
  Advertise = 0,
  Store = 1,
}
export enum SelectedMarketType {
  All = 0,
  Advertise = 1,
  Store = 2,
}
export enum CustomDomainStatus {
  Requested = 0,
  Checking = 1,
  Approved = 2,
  Rejected = 3,
}
export enum InsightPeriod {
  Daily,
  Weekly,
  Monthly,
  Yearly,
}
